services:
  proxy:
    image: nginx:alpine
    configs:
      - source: proxy_config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - fe
      - api
    networks:
      front-tier:
        ipv4_address: 172.16.0.2
    ports:
      - "80:80"
    restart: unless-stopped

  fe:
    image: dateproj/fe
    build: dateproj-fe
    networks:
      front-tier:
        ipv4_address: 172.16.0.3
        aliases:
          - dateproj-fe
    restart: unless-stopped

  api:
    image: dateproj/api
    build: 
      context: dateproj-api
      dockerfile: multi.Dockerfile
    networks:
      front-tier:
        ipv4_address: 172.16.0.4
        aliases:
          - dateproj-api
      back-tier:
        ipv4_address: 172.16.1.4
    restart: unless-stopped

configs:
  proxy_config:
    file: dateproj-proxy/dateproj.conf

networks:
  front-tier:
    ipam:
       config:
         - subnet: "172.16.0.0/24"
  back-tier:
    ipam:
       config:
         - subnet: "172.16.1.0/24"
