services:
  fe:
    image: dateproj/fe
    build: dateproj-fe
    networks:
      front-tier:
        ipv4_address: 172.16.0.2
    restart: unless-stopped

networks:
  front-tier:
    ipam:
       config:
         - subnet: "172.16.0.0/24"
  back-tier:
    ipam:
       config:
         - subnet: "172.16.1.0/24"
